# %% [markdown]
# # 07 · The 2015–2016 Tasman Sea marine heatwave
# A Julia reproduction of the author's [original MATLAB example](https://github.com/ZijieZhaoMMHW/MHW_tracking/blob/main/example.md): the complete 230-day event, daily spatial normalization with and without the surrounding SST field, five normalized times, and all three animations.
# The five original MAT files remain MAT files. `load_matlab_tracks` converts the scalar MATLAB struct/cell arrays into Julia `Track3D` values; lon×lat×time ordering, one-based spatial indices, and absolute day labels are preserved. `norm_flag` is the **fifth** argument to `spn`.
# %%
include(isfile("bootstrap.jl") ? "bootstrap.jl" : "notebooks/bootstrap.jl")
using Dates, Base64
include(joinpath(ROOT,"examples","tasman_data.jl"))
include(joinpath(ROOT,"notebooks","tasman_visuals.jl"))
DATA_DIR=get(ENV,"MHW_TASMAN_DATA_DIR",joinpath(ROOT,"data","tasman_sea"))
tasman=load_tasman_data(DATA_DIR)
dates=Date(1982,1,1).+Day.(tasman.track.day.-1)
@test size(tasman.anomaly)==(400,160,230)
@test dates[[1,end]]==[Date(2015,10,3),Date(2016,5,19)]
@test all(diff(tasman.track.day).==1)
println("Event dates: ",first(dates)," to ",last(dates)," | days: ",length(dates),
    " | split records: ",length(tasman.track.split_day))
println("SST anomaly input: ",size(tasman.anomaly)," | units: °C, as documented by the author")
# %% [markdown]
# ## Event history and input SST anomaly
# Calendar dates follow the original example's 1982-01-01 origin. `data_anom[:,:,1]` aligns with absolute track day 12329, not day 1 of the full 1982–2020 record. No tracking is repeated: this is the supplied event itself.
# Daily size is a count of grid cells, not an area estimate. The SST average uses the event's occupied input cells with finite values. Split records retain the original algorithm's definition.
# %%
daily_size=length.(tasman.track.xloc)
mean_sst=[mean(filter(isfinite,[tasman.anomaly[Int(x),Int(y),j] for (x,y) in zip(tasman.track.xloc[j],tasman.track.yloc[j])])) for j in 1:230]
persistent_missing=dropdims(all(isnan,tasman.anomaly;dims=3);dims=3)
chosen=[1,77,154,230]
ticks=([1,31,62,93,124,155,186,217],string.(dates[[1,31,62,93,124,155,186,217]]))
fig=Figure(size=(1150,440))
ax=Axis(fig[1,1],title="Original event size",xlabel="Calendar date",ylabel="Occupied grid cells",xticks=ticks,xticklabelrotation=pi/4)
lines!(ax,1:230,daily_size;color=:crimson,linewidth=2)
vlines!(ax,tasman.track.split_day.-first(tasman.track.day).+1;color=(:gray30,0.18),linewidth=1)
ax2=Axis(fig[1,2],title="SST anomaly within the tracked event",xlabel="Calendar date",ylabel="Mean SST anomaly (°C)",xticks=ticks,xticklabelrotation=pi/4)
lines!(ax2,1:230,mean_sst;color=:darkorange,linewidth=2)
Label(fig[0,:],"Tasman Sea · 2015-10-03 to 2016-05-19 · 230 days · 38 split records",fontsize=20)
emit_figure(fig,"07_tasman_history")
# %% [markdown]
# ## Run the full spatial and temporal normalization
# Both flags operate on the complete 400×160×230 SST anomaly array. The radius is the event's maximum distance from its daily arithmetic centers over its entire lifetime; it stays fixed while the center moves. Each day produces a 100×100 polar field.
# Results below come from actual Julia calculations. A matching input/code SHA256 fingerprint permits reuse of the saved full outputs, avoiding repeated expensive calculations while exploring figures. Set `MHW_TASMAN_RECOMPUTE=1` to recompute both flags; changed inputs or package source invalidate the cache automatically. Reported timings measure those original calculations, including compilation if required.
# %%
recompute=get(ENV,"MHW_TASMAN_RECOMPUTE","0")=="1"
measured=[run_or_load_tasman_spn(tasman,flag;output_dir=joinpath(ROOT,"validation","results"),recompute) for flag in 0:1]
tasman_results=getproperty.(measured,:output)
for (flag,m) in enumerate(measured)
    @test size(m.output[2][1])==(100,100,230)
    @test size(m.output[3])==(100,100,5,1,1)
    println("norm_flag=",flag-1," | radius km=",only(m.output[1])," | measured Julia seconds=",m.seconds," | reused verified cache=",m.cached)
end
geometry=polar_mesh(tasman_results[1][4],tasman_results[1][5])
# %% [markdown]
# ## Full MATLAB comparison, including NaN and zero locations
# Fresh references were generated by executing the preserved original `spn.m` on these exact files under both flags. Compare all five outputs across all 230 days, including the five time-normalized fields. Numerical tolerances are 1e-10 absolute and 1e-11 relative; radii use 1e-12 relative. NaN and zero masks must match exactly.
# Large MATLAB references are local validation files. If absent after cloning, this cell explicitly reports NOT RUN; the Julia workflow and figures remain runnable with the original input files.
# %%
tasman_errors=NamedTuple[]
for flag in 0:1
    path=joinpath(ROOT,"validation","results","matlab_tasman_spn_$flag.mat")
    if !isfile(path)
        println("NOT RUN: full MATLAB reference for norm_flag=$flag is absent")
        continue
    end
    f=matread(path); actual=tasman_results[flag+1]
    @test isapprox(actual[1],vecmat(f["radius"]);atol=1e-10,rtol=1e-12)
    fields=(("daily",actual[2][1],only(vec(f["snapshots"]))),
        ("time-normalized",actual[3],reshape(f["normalized"],100,100,5,1,1)),
        ("unit x",actual[4],f["xunit"]),("unit y",actual[5],f["yunit"]))
    for (name,a,b) in fields
        @test float_match(a,b)
        err=field_error(a,b)
        @test err.nan_mismatch==0 && err.zero_mismatch==0
        push!(tasman_errors,(flag=flag,field=name,err...))
    end
end
println("Full event MATLAB comparisons: ",tasman_errors)
# %% [markdown]
# ## Geographic event evolution on the original grid
# Four snapshots show the full source domain, SST anomaly in °C, and the tracked event outline. Gray means missing input values; geographic land and missing data are not inferred from the unrelated global ocean mask. CairoMakie replaces MATLAB's `m_map` plotting dependency. Scientific coordinates and values are retained; styling is adapted to Julia.
# %%
fig=Figure(size=(1200,720))
for (p,j) in enumerate(chosen)
    ax=Axis(fig[cld(p,2),mod1(p,2)],title="$(dates[j]) · $(daily_size[j]) MHW cells",xlabel="Longitude (deg E)",ylabel="Latitude (deg N)",aspect=DataAspect())
    heatmap!(ax,tasman.lon,tasman.lat,tasman.anomaly[:,:,j];colormap=:balance,colorrange=(-5,5),nan_color=:lightgray)
    contour!(ax,tasman.lon,tasman.lat,tasman_mask(tasman,j);levels=[0.5],color=:black,linewidth=1.5)
end
Colorbar(fig[:,3];colormap=:balance,limits=(-5,5),label="SST anomaly (°C)")
Label(fig[0,:],"Original geographic input · black outline: supplied MHW event",fontsize=20)
emit_figure(fig,"07_tasman_geographic")
# %% [markdown]
# ## With and without the surrounding field
# The upper row is `norm_flag=0`: values outside the compact event boundary are zero. The lower row is `norm_flag=1`: surrounding SST anomalies remain, with missing input shown gray. This is not a land-mask switch.
# A triangular mesh uses the actual polar x/y coordinates; the radial/angular indices are never plotted as a Cartesian heatmap. As in the source example, the color scale is 0–5 °C. Values below 0 or above 5 are retained numerically and clipped only by this display scale.
# %%
fig=Figure(size=(1350,750))
for flag in 0:1, (c,j) in enumerate(chosen)
    polar_panel(fig[flag+1,c],geometry,tasman_results[flag+1][2][1][:,:,j];title="flag=$flag · $(dates[j])")
end
Colorbar(fig[:,5];colormap=:thermal,limits=(0,5),label="SST anomaly (°C)",ticks=0:1:5)
Label(fig[0,:],@sprintf("Full-event maximum radius: %.2f km · same radius on all 230 days",only(tasman_results[1][1])),fontsize=20)
emit_figure(fig,"07_tasman_spatial_flags")
# %% [markdown]
# ## Five normalized times for composite analysis
# Daily polar fields are resampled to 0, 0.25, 0.5, 0.75, and 1, reproducing the original five-time output. The original time nodes are `(1:230)/230`; t=0 therefore extrapolates beyond the first sample and is not simply a copy of the first day.
# %%
fig=Figure(size=(1450,630))
for flag in 0:1, j in 1:5
    polar_panel(fig[flag+1,j],geometry,tasman_results[flag+1][3][:,:,j,1,1];title="flag=$flag · normalized t=$((j-1)/4)")
end
Colorbar(fig[:,6];colormap=:thermal,limits=(0,5),label="SST anomaly (°C)",ticks=0:1:5)
emit_figure(fig,"07_tasman_normalized_time")
# %% [markdown]
# ## The author's separate global smoothing example
# `snaps.mat` and `ocean_idx.mat` are 144×72 on a 2.5° global grid; they are not the Tasman Sea mask or anomaly grid. Reproduce `example_used.m`: finite snapshot positions become active; land centers are NaN; `grid_nearby_index(...,2.5)` defines a 5° coordinate window; `convzz` averages valid neighbors; values ≥0.5 become active.
# The original method is a coordinate-window average, not a nearest-k-neighbor algorithm. Land is masked gray for display; the computed threshold array retains the source's false values on land.
# %%
raw_snap=matread(joinpath(DATA_DIR,"snaps.mat"))["snaps"]
ocean=matread(joinpath(DATA_DIR,"ocean_idx.mat"))["ocean_idx"]
global_lon=collect(1.25:2.5:360); global_lat=collect(-88.75:2.5:90)
binary=Float64.(.!isnan.(raw_snap)); binary[.!ocean].=NaN
near=grid_nearby_index(global_lon,global_lat,2.5)
fraction=convzz(binary,near,ocean)
smoothed=Float64.(fraction.>=0.5)
path=joinpath(ROOT,"validation","results","matlab_tasman_smoothing.mat")
if isfile(path)
    f=matread(path)
    @test all(near[k]==vecmat(f["near"][k]) for k in eachindex(near))
    @test float_match(fraction,f["fraction"])
    @test smoothed==f["smoothed"]
    println("Original global smoothing: neighbor order, numeric field and threshold mask match MATLAB.")
else
    println("NOT RUN: original global smoothing MATLAB reference absent")
end
fig=Figure(size=(1350,390))
for (c,(name,field)) in enumerate((("Raw presence",binary),("5° neighborhood fraction",fraction),("Threshold ≥0.5",smoothed)))
    shown=copy(field); shown[.!ocean].=NaN
    ax=Axis(fig[1,c],title=name,xlabel="Longitude (deg E)",ylabel="Latitude (deg N)",aspect=DataAspect())
    heatmap!(ax,global_lon,global_lat,shown;colormap=[:white,:royalblue],colorrange=(0,1),nan_color=:lightgray)
end
Colorbar(fig[2,:];vertical=false,colormap=[:white,:royalblue],limits=(0,1),label="Active fraction / binary presence")
emit_figure(fig,"07_original_global_smoothing")
# %% [markdown]
# ## All 230 days as three animations
# Reproduce the original three GIFs: event geometry, geometry beside `norm_flag=0`, and geometry beside `norm_flag=1`. Every animation contains all 230 calendar dates at two frames per second, matching the original 0.5-second delay. The geographic background marks values missing on every input day; it does not substitute the unrelated global ocean mask.
# GIFs are generated by Julia/CairoMakie and embedded below for standalone HTML viewing. Set `MHW_TASMAN_RENDER_GIFS=0` to skip regeneration when the three GIFs already exist. Standalone PNG/PDF snapshots are also saved above.
# %%
animations=joinpath(ROOT,"notebooks","animations"); mkpath(animations)
for (name,flag) in (("07_tasman_event",nothing),("07_tasman_norm0",0),("07_tasman_norm1",1))
    path=joinpath(animations,name*".gif")
    if get(ENV,"MHW_TASMAN_RENDER_GIFS","1")=="1" || !isfile(path)
        println("Rendering ",name," · all 230 frames"); flush(stdout)
        result=flag===nothing ? nothing : tasman_results[flag+1]
        record_tasman_gif(tasman,dates,persistent_missing,geometry,result,flag,path)
    end
    display(EmbeddedTasmanGIF(path,"$name · 230 days · 0.5 s/frame"))
end
println("Complete original example reproduced: five original MAT inputs, both flags, five normalized times, global smoothing, and three full-event GIFs.")
